field.storage_settings.og_standard_reference:
  type: field.storage_settings.entity_reference
  label: 'Organic Groups reference field storage settings'

field.field_settings.og_standard_reference:
  type: field.field_settings.entity_reference
  label: 'Organic Groups reference field settings'

entity_reference_selection.og:default:
  type: entity_reference_selection.default
  label: 'The OG selection handler settings'

og.settings:
  type: config_object
  label: 'Organic Groups settings'
  mapping:
    groups:
      type: sequence
      sequence:
        type: og.settings.group.[%key]
    group_manager_full_access:
      type: boolean
      label: 'Full access for group managers'
    node_access_strict:
      type: boolean
      label: 'Strict node access permissions'
    delete_orphans:
      type: boolean
      label: 'Delete orphaned group content when a group is deleted'
    delete_orphans_plugin_id:
      type: string
      label: 'The method to use when deleting orphaned group content'
    deny_subscribe_without_approval:
      type: boolean
      label: 'When enabled, a user that ask to join to a private group their membership status will be pending regardless of the group permissions'
    group_resolvers:
      type: sequence
      label: 'List of OgGroupResolver plugins that are used to discover the group context, in order of priority.'
      sequence:
        type: string
        label: 'OgGroupResolver plugin ID.'

og.settings.group.*:
  type: sequence
  label: 'OG groups'
  sequence:
    type: string
    label: 'Group'

og.og_membership_type.*:
  type: config_entity
  label: 'OG membership type'
  mapping:
    type:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    description:
      type: string
      label: 'Description'
    status:
      type: boolean
      label: 'Status'

# Copied and adapted from user.schema.yml
og.og_role.*:
  type: config_entity
  label: 'OG user role settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'User role weight'
    group_id:
      type: string
      label: 'Group ID'
    group_type:
      type: string
      label: 'Group type'
    group_bundle:
      type: string
      label: 'Group bundle'
    is_admin:
      type: boolean
      label: 'User is group admin'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        type: string
        label: 'Permission'
    role_type:
      type: string
      label: 'Role type'

field.widget.settings.og_complex:
  type: field.widget.settings.entity_reference_autocomplete
  label: 'OG Group Audience field widget'
  mapping:
    # This already exists in field.widget.settings.entity_reference_autocomplete
    # in Drupal 8.8.x and is added here just to ensure backwards compatibility
    # with Drupal 8.7.x.
    # @todo Remove this entry in https://github.com/Gizra/og/issues/581
    # @see https://github.com/Gizra/og/issues/581
    match_limit:
      type: integer
      label: 'Maximum number of autocomplete suggestions.'

views.field.og_membership_bulk_form:
  type: views_field_bulk_form
  label: 'OG Membership bulk form'

action.configuration.og_membership_add_multiple_roles_action:
  type: action_configuration_default
  label: 'Add roles to the selected membership(s)'

action.configuration.og_membership_add_single_role_action:
  type: action_configuration_default
  label: 'Add a role to a group member'

action.configuration.og_membership_approve_pending_action:
  type: action_configuration_default
  label: 'Approve the pending membership(s)'

action.configuration.og_membership_block_action:
  type: action_configuration_default
  label: 'Block the selected membership(s)'

action.configuration.og_membership_delete_action:
  type: action_configuration_default
  label: 'Delete the selected membership(s)'

action.configuration.og_membership_remove_single_role_action:
  type: action_configuration_default
  label: 'Remove a role to a group member'

action.configuration.og_membership_remove_multiple_roles_action:
  type: action_configuration_default
  label: 'Remove roles from the selected membership(s)'

action.configuration.og_membership_unblock_action:
  type: action_configuration_default
  label: 'Unblock the selected membership(s)'

condition.plugin.og_group_type:
  type: condition.plugin
  mapping:
    group_types:
      type: sequence
      sequence:
        type: string

block.settings.og_member_count:
  type: block_settings
  label: 'Group member count block'
  mapping:
    count_blocked_users:
      type: boolean
      label: 'Count blocked users'
    count_pending_users:
      type: boolean
      label: 'Count pending users'
