field.storage_settings.og_membership_reference:
  type: mapping
  label: 'Organic Groups reference field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of entity to reference'

field.field_settings.og_membership_reference:
  type: mapping
  label: 'Organic Groups reference field settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Organic Groups reference selection plugin settings'
    access_override:
      type: boolean
      label: 'Access Override'

field.storage_settings.og_standard_reference:
  type: mapping
  label: 'Organic Groups reference field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of entity to reference'

field.field_settings.og_standard_reference:
  type: mapping
  label: 'Organic Groups reference field settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Organic Groups reference selection plugin settings'
    access_override:
      type: boolean
      label: 'Access Override'

og.settings:
  type: config_object
  label: 'Organic Groups settings'
  mapping:
    groups:
      type: sequence
      sequence:
        type: og.settings.group.[%key]
    group_manager_full_access:
      type: boolean
      label: 'Full access for group managers'
    node_access_strict:
      type: boolean
      label: 'Strict node access permissions'
    orphans_delete:
      type: boolean
      label: 'Delete orphaned group content when a group is deleted'
    use_queue:
      type: boolean
      label: 'Use queue'

og.settings.group.*:
  type: sequence
  label: 'OG groups'
  sequence:
    type: string
    label: 'Group'

og.og_membership_type.*:
  type: config_entity
  label: 'OG membership type'
  mapping:
    type:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    description:
      type: string
      label: 'Description'
    status:
      type: boolean
      label: 'Status'

# Copied and adapted from user.schema.yml
og.og_role.*:
  type: config_entity
  label: 'OG user role settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'User role weight'
    group_id:
      type: string
      label: 'Group ID'
    group_type:
      type: label
      label: 'Group type'
    group_bundle:
      type: label
      label: 'Group bundle'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        type: string
        label: 'Permission'

field.widget.settings.og_complex:
  type: mapping
  label: 'OG Group Audience field widget'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'
